#' Get a lazy data frame for a given table or view reference.
#'
#' @details This function generates a dplyr lazy tbl object from a table or view reference in a listed_connection object generated by db_connect.
#' This is useful for creating an sql query with dplyr syntax.
#'
#' @param ref a table reference from db_connect
#' @param conn a connection object from db_connect. Defaults to `db$conn`.
#'
#' @return a dplyr tbl object
#' @export
#'
#'
get_lazy <- function(ref, conn = db$conn){
  dbplyr::in_schema(ref$table_schema, ref$table_name) %>%
    dplyr::tbl(conn, .) %>%
    return()
}
